### ISSUE TITLE
Hoe selecteer ik een database?

### ISSUE THREAD

**Issue by YoloLiena** [ICT-Academie/readers#18]
Op pagina 8 moet ik ook een database nog selecteren, hoe doe ik dat?

**Comment by koffiebaard** [comment]
Om te zorgen dat de queries in een specifieke database uitgevoerd worden, kan je dubbelklikken op de database. In de balk links ga je naar de tab "schemas" en dubbelklik je op de database "pokedex".

De select query waar het verder over gaat (op pagina 8) gaat over het ophalen van informatie uit de tabellen in de database. De queries kan je in het query venster in MySQL Workbench neerzetten en uitvoeren met het bliksem icoontje erboven.

Ik hoop dat dit helpt voor nu, ik zal komende week de reader aanpassen om dit duidelijker te maken.
