### ISSUE TITLE
Database basisbegrippen "Zoek op adhv de naam" 

### ISSUE THREAD

**Issue by YoloLiena** [ICT-Academie/readers#20]
Bij opdracht 3.6 - 1 was de vraag "Maak een query die alleen Charmander laat zien. Toon alle velden uit pokemon . Je kan Charmander
opzoeken adhv zijn naam." Sinds dit een nieuw onderwerp is wist ik nog niet alle tips & tricks en had ik geen flauw idee hoe dit moest. Nu heb ik ontdekt dat je "Where name = 'charmander' " moet doen, maar nergens in de tekst / screenshots kon ik vinden dat het dus als 'charmander' moest met normale ' tekens. Misschien is het een idee om dat erin te verwerken?

**Comment by koffiebaard** [comment]
Dat was bedoelt als een uitdaging in de opdrachten, dus ik heb het niet expliciet voorgezegd in de nieuwe reader update. Het vermeld nu dat je directe vergelijkingen kan doen met het = teken, en in de tekst staat dat strings met aanhalingstekens moeten.
